"""
Vitals Simulator — Kafka producer for Sentinel Health Agent.

Sends one simulated vitals reading per patient per interval cycle,
round-robining through all registered patients so the backend sees
data for every patient at roughly the same frequency.

Configuration (all via environment variables or .env):
    KAFKA_BOOTSTRAP_SERVERS  — broker address  (default: localhost:9092)
    KAFKA_CONSUMER_TOPIC     — topic to publish (default: vitals_stream)
    SEND_INTERVAL_SECONDS    — seconds between full cycles (default: 2)
    CRITICAL_CHANCE          — probability of CRITICAL alert (default: 0.10)
    WARNING_CHANCE           — probability of WARNING alert  (default: 0.15)

Usage:
    python simulator.py

Patient IDs:
    Add your registered patient IDs to PATIENT_IDS below.
    IDs are auto-generated by the Patient Onboarding page (e.g. PAT-3F2A1B4C).
"""
import json
import logging
import os
import random
import signal
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

from dotenv import load_dotenv
from kafka import KafkaProducer
from kafka.errors import KafkaError

load_dotenv()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(message)s",
    datefmt="%H:%M:%S",
    stream=sys.stdout,
)
logger = logging.getLogger("simulator")

# ---------------------------------------------------------------------------
# Patient pool — add / remove patient IDs here freely.
# These must match IDs that exist in your patients table.
# After registering a patient via the dashboard, copy the auto-generated
# ID (e.g. PAT-3F2A1B4C) into this list.
# ---------------------------------------------------------------------------
PATIENT_IDS: list[str] = [
    "PAT-BE0E9B91",
]

# ---------------------------------------------------------------------------
# Configuration — override via environment variables
# ---------------------------------------------------------------------------
KAFKA_SERVER: str       = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
TOPIC_NAME: str         = os.getenv("KAFKA_CONSUMER_TOPIC", "vitals_stream")
SEND_INTERVAL: float    = float(os.getenv("SEND_INTERVAL_SECONDS", "2"))
CRITICAL_CHANCE: float  = float(os.getenv("CRITICAL_CHANCE", "0.10"))
WARNING_CHANCE: float   = float(os.getenv("WARNING_CHANCE", "0.15"))

# Validate probability config at startup
if CRITICAL_CHANCE + WARNING_CHANCE >= 1.0:
    raise ValueError(
        f"CRITICAL_CHANCE ({CRITICAL_CHANCE}) + WARNING_CHANCE ({WARNING_CHANCE}) "
        f"must be less than 1.0"
    )

# Pre-compute NORMAL threshold once rather than every call to generate_vitals
_WARNING_THRESHOLD: float = CRITICAL_CHANCE + WARNING_CHANCE

# Status icons for terminal output
_STATUS_ICON: dict[str, str] = {"CRITICAL": "🔴", "WARNING": "🟡", "NORMAL": "🟢"}


# ---------------------------------------------------------------------------
# Vitals generation
# ---------------------------------------------------------------------------

@dataclass
class VitalsReading:
    """A single simulated vitals reading for one patient."""
    patient_id: str
    timestamp: str
    heart_rate: int
    spo2: int
    status: str

    def to_dict(self) -> dict:
        return {
            "patient_id": self.patient_id,
            "timestamp":  self.timestamp,
            "heart_rate": self.heart_rate,
            "spo2":       self.spo2,
            "status":     self.status,
        }


def generate_vitals(patient_id: str) -> VitalsReading:
    """
    Generate a simulated vitals reading with realistic probability distribution.

    Alert probabilities (configurable via env vars):
      - CRITICAL (~10%) : HR 121–160 BPM — tachycardia
      - WARNING  (~15%) : HR 101–120 BPM — elevated
      - NORMAL   (~75%) : HR  60– 99 BPM — healthy range
    """
    roll = random.random()

    if roll < CRITICAL_CHANCE:
        heart_rate, status = random.randint(121, 160), "CRITICAL"
    elif roll < _WARNING_THRESHOLD:
        heart_rate, status = random.randint(101, 120), "WARNING"
    else:
        heart_rate, status = random.randint(60, 99), "NORMAL"

    return VitalsReading(
        patient_id=patient_id,
        timestamp=datetime.now(timezone.utc).isoformat(),
        heart_rate=heart_rate,
        spo2=random.randint(94, 99),
        status=status,
    )


# ---------------------------------------------------------------------------
# Kafka producer
# ---------------------------------------------------------------------------

def build_producer() -> Optional[KafkaProducer]:
    """
    Create and return a KafkaProducer, or None if the broker is unreachable.

    Producer is tuned for small, frequent messages:
      - acks="all"          → durability: leader + all in-sync replicas confirm
      - linger_ms=20        → batch messages within a 20 ms window (fewer syscalls)
      - batch_size=16_384   → 16 KB batch cap — plenty for vitals payloads
      - compression_type    → gzip reduces wire size by ~60-70% on JSON
      - retries=5           → automatic retry on transient broker errors
    """
    try:
        producer = KafkaProducer(
            bootstrap_servers=[KAFKA_SERVER],
            value_serializer=lambda v: json.dumps(v).encode("utf-8"),
            key_serializer=lambda k: k.encode("utf-8") if k else None,
            acks="all",
            retries=5,
            retry_backoff_ms=500,
            linger_ms=20,
            batch_size=16_384,
            compression_type="gzip",
        )
        logger.info(f"✅ Connected to Kafka at {KAFKA_SERVER}")
        return producer
    except KafkaError as exc:
        logger.error(f"❌ Could not connect to Kafka: {exc}")
        return None


def on_send_error(exc: Exception) -> None:
    """Callback invoked by the Kafka producer on a failed async send."""
    logger.error(f"❌ Kafka send error: {exc}")


def _get_total_sent(producer: KafkaProducer) -> int:
    """Safely read the cumulative sent-message count from producer metrics."""
    try:
        for _name, metric in producer.metrics().items():
            if isinstance(metric, dict) and "record-send-total" in metric:
                return int(metric["record-send-total"])
    except Exception:
        pass
    return -1  # unknown — avoids crashing the shutdown log


# ---------------------------------------------------------------------------
# Main simulation loop
# ---------------------------------------------------------------------------

def run_simulator() -> None:
    """
    Publish one vitals reading per patient per cycle until Ctrl+C / SIGTERM.

    Round-robins through all patients in PATIENT_IDS on every cycle so
    the backend and dashboard always see fresh data for every patient,
    regardless of how many are registered.

    The patient_id is used as the Kafka message key so all readings for
    the same patient land on the same partition (preserving ordering).
    """
    if not PATIENT_IDS:
        logger.error("PATIENT_IDS list is empty. Add at least one patient ID and restart.")
        sys.exit(1)

    producer = build_producer()
    if producer is None:
        sys.exit(1)

    # ── Graceful shutdown via OS signals ─────────────────────────────────
    _stop = False

    def _handle_signal(sig, _frame):
        nonlocal _stop
        logger.info(f"\n⚠️  Signal {sig} received — finishing current cycle then stopping...")
        _stop = True

    signal.signal(signal.SIGINT,  _handle_signal)
    signal.signal(signal.SIGTERM, _handle_signal)

    # ── Startup banner ────────────────────────────────────────────────────
    logger.info(
        f"🚀 Simulator started  |  topic: {TOPIC_NAME}  |  "
        f"patients: {len(PATIENT_IDS)}  |  interval: {SEND_INTERVAL}s / cycle"
    )
    logger.info(f"   Pool  : {PATIENT_IDS}")
    logger.info(
        f"   Rates : CRITICAL={CRITICAL_CHANCE:.0%}  "
        f"WARNING={WARNING_CHANCE:.0%}  "
        f"NORMAL={(1 - CRITICAL_CHANCE - WARNING_CHANCE):.0%}"
    )
    logger.info("   Ctrl+C to stop\n")

    sent = 0
    cycle = 0

    try:
        while not _stop:
            cycle += 1
            cycle_start = time.monotonic()

            # Send one reading per patient in this cycle
            for patient_id in PATIENT_IDS:
                if _stop:
                    break

                reading = generate_vitals(patient_id)

                # Use patient_id as Kafka key → same patient always routes to
                # the same partition, preserving per-patient message ordering
                producer.send(
                    TOPIC_NAME,
                    key=patient_id,
                    value=reading.to_dict(),
                ).add_errback(on_send_error)

                sent += 1
                icon = _STATUS_ICON.get(reading.status, "⚪")
                logger.info(
                    f"{icon} [cycle {cycle:04d} | #{sent:05d}]  "
                    f"Patient: {patient_id:<14}  |  "
                    f"HR: {reading.heart_rate:>3} BPM  |  "
                    f"SpO2: {reading.spo2}%  |  "
                    f"{reading.status}"
                )

            # Sleep for the remainder of the interval so the cycle time stays
            # constant even if sending multiple patients takes a little time
            elapsed = time.monotonic() - cycle_start
            sleep_time = max(0.0, SEND_INTERVAL - elapsed)
            if sleep_time > 0:
                time.sleep(sleep_time)

    finally:
        total = _get_total_sent(producer)
        sent_label = str(total) if total >= 0 else "unknown"
        logger.info(f"\n🛑 Flushing {sent_label} buffered message(s)...")
        producer.flush(timeout=10)
        producer.close()
        logger.info(f"✅ Shutdown complete. Total readings sent this session: {sent}")


if __name__ == "__main__":
    run_simulator()

