import os

# DB
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_USER_NAME = os.getenv("POSTGRES_USER_NAME")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_CLINICAL_ALERTS_TABLE = os.getenv("POSTGRES_CLINICAL_ALERTS_TABLE")
DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER_NAME}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

# Kafka
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_CONSUMER_TOPIC = os.getenv("KAFKA_CONSUMER_TOPIC")

#Ollama
OLLAMA_HOST = os.getenv("OLLAMA_HOST")
NO_PROXY = os.getenv("NO_PROXY")
MEDICAL_EMBEDDING = os.getenv("MEDICAL_EMBEDDING")
